config/routes.rb
Lmsn2::Application.routes.draw do

  resources :song_requests do
    get 'archive', :on => :member
    get 'unarchive', :on => :member
  end

  resources :singers
  
  resource :songlist, :except => [:create, :edit, :delete] do
    get 'import','export'
    post 'load'
  end

  resources :djs, :except => [:new, :create] do
    resources :songs do
      match 'request' => 'song_requests#new'
      get 'search', :on => :collection
      resources :song_requests, :only => :new
    end
    resources :artists, :only => [:index,:show]
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "pages#index"
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /djs/:dj_id/artists
  # GET /djs/:dj_id/artists.json
  def index
    @dj = Dj.find(params[:dj_id])
    @artists = @dj.artists.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /djs/:dj_id/artists/:id
  # GET /djs/:dj_id/artists/:id.json
  def show
    @dj = Dj.find(params[:dj_id])
    @artist = params[:id]
    @songs = @dj.songs_by_artist(@artist).page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @songs }
    end
  end

end

app/views/artists/index.html.erb
<h1><%= @dj.name %> - Artists</h1>
<%= paginate @artists %>
<ul>
<% @artists.each do |artist| %>
    <li><%= link_to artist.artist+' ('+artist.count.to_s+')', dj_artist_path(@dj,URI.escape(artist.artist,/\W/)) %></li>
<% end %>
</ul>
<%= paginate @artists %>

app/views/artists/show.html.erb
<h1><%= @dj.name %> - Songs by <%= @artist %></h1>
<%= paginate @songs %>
<table>
  <tr>
    <th>Artist</th>
    <th>Title</th>
    <th>Disc</th>
    <th>Identifier</th>
    <!--<th>Notes</th>-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.artist %></td>
    <td><%= song.title %></td>
    <td><%= song.disc %></td>
    <td><%= song.identifier %></td>
    <!--<td><%= song.notes %></td>-->
    <td><%= link_to 'Show', [@dj,song] %></td>
    <td><%= link_to 'Edit', edit_dj_song_path(@dj,song) %></td>
    <td><%= link_to 'Delete', [@dj,song], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @songs %>
<br />