config/routes.rb
Lmsn2::Application.routes.draw do

  resources :song_requests do
    get 'archive', :on => :member
    get 'unarchive', :on => :member
  end

  resources :singers
  
  resource :songlist, :except => [:create, :edit, :delete] do
    get 'import','export'
    post 'load'
  end

  resources :djs, :except => [:new, :create] do
    resources :songs do
      match 'request' => 'song_requests#new'
      get 'search', :on => :collection
      resources :song_requests, :only => :new
    end
    resources :artists, :only => [:index,:show]
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "pages#index"
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/singer.rb
class Singer < ActiveRecord::Base
  belongs_to :user, :dependent => :destroy
  has_many :song_requests, :dependent => :destroy
end
# == Schema Information
#
# Table name: singers
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  load_and_authorize_resource
  # GET /singers
  # GET /singers.json
  def index
    @singers = Singer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @singers }
    end
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
    @singer = Singer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @singer }
    end
  end

  # GET /singers/new
  # GET /singers/new.json
  def new
    @singer = Singer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @singer }
    end
  end

  # GET /singers/1/edit
  def edit
    @singer = Singer.find(params[:id])
    if @singer.name.blank?
      flash.now[:info] = "Set the name that you'd like the DJ to call you by."
    end
  end

  # POST /singers
  # POST /singers.json
  def create
    @singer = Singer.new(params[:singer])

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render json: @singer, status: :created, location: @singer }
      else
        format.html { render action: "new" }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /singers/1
  # PUT /singers/1.json
  def update
    @singer = Singer.find(params[:id])

    respond_to do |format|
      if @singer.update_attributes(params[:singer])
        format.html { redirect_to root_path, notice: 'Your preferences were successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    @singer = Singer.find(params[:id])
    @singer.destroy

    respond_to do |format|
      format.html { redirect_to singers_url }
      format.json { head :ok }
    end
  end
end

app/views/singers/_form.html.erb
<%= form_for(@singer) do |f| %>
  <% if @singer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
      <% @singer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/singers/edit.html.erb
<h1>Preferences</h1>

<%= render 'form' %>

app/views/singers/index.html.erb
<h1>Listing singers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @singers.each do |singer| %>
  <tr>
    <td><%= singer.name %></td>
    <td><%= singer.user_id %></td>
    <td><%= link_to 'Show', singer %></td>
    <td><%= link_to 'Edit', edit_singer_path(singer) %></td>
    <td><%= link_to 'Destroy', singer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Singer', new_singer_path %>

app/views/singers/new.html.erb
<h1>New singer</h1>

<%= render 'form' %>

<%= link_to 'Back', singers_path %>

app/views/singers/show.html.erb
<h2>Singer Profile</h2>

<p>
  <b>Name:</b>
  <%= @singer.name %> (<%= link_to 'edit', [:edit,@singer] %>)
</p>

<p>
  <b>Email:</b>
  <%= @singer.user.email %> (<%= link_to 'edit', edit_user_registration_path %>)
</p>

<%= link_to 'Back', root_path %>