config/routes.rb
Lmsn2::Application.routes.draw do

  resources :song_requests do
    get 'archive', :on => :member
    get 'unarchive', :on => :member
  end

  resources :singers
  
  resource :songlist, :except => [:create, :edit, :delete] do
    get 'import','export'
    post 'load'
  end

  resources :djs, :except => [:new, :create] do
    resources :songs do
      match 'request' => 'song_requests#new'
      get 'search', :on => :collection
      resources :song_requests, :only => :new
    end
    resources :artists, :only => [:index,:show]
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "pages#index"
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/controllers/songlists_controller.rb
class SonglistsController < ApplicationController
  authorize_resource :class => false
  before_filter :set_dj

  def set_dj
    @dj = current_user.dj
  end

  # GET /songlist
  def show
    if @dj.songs.empty?
      flash.now[:info] = "Import a songlist to get started."
    end
  end

  # GET /songlist/import
  def import
  end

  # GET /songlist/export
  def export
  end

  # PUT /songlist
  # upload file
  def update
    respond_to do |format|
      unless @dj.update_attributes(params[:dj])
        format.html { render action: :import }
        format.json { head :ok }
      else
        format.html { render action: :import }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /songlist/load
  # load songs from file into @dj.songs
  def load
    if params[:replace]
      @dj.destroy_all_songs
    end
    
    respond_to do |format|
      if @dj.load_songlist(@dj.songlist.path)
        format.html { redirect_to songlist_path, notice: 'Songlist successfully imported' }
        format.json { head :ok }
      else
        format.html { render action: :import }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

 ## DELETE /songlist
 #def destroy
 #  #delete file and remove dj.songlist
 #  respond_to do |format|
 #    format.html { redirect_to djs_url }
 #    format.json { head :ok }
 #  end
 #end
end

app/helpers/mobile_helper.rb
#Helpers for mobile views
module MobileHelper

end

app/views/mobile/songlists/export.html.erb
<h2>Export Songlist</h2>
<%= jqm_listview do %>
  <%= li_link_to "Download json version", dj_songs_path(@dj,:format => :json), :rel => :external %>
<% end %>

app/views/mobile/songlists/import.html.erb
<h2>Import Songs</h2>
<p>We can automatically import songs from a csv file. Don't worry if you don't know what this means, or your songlist is in a different format. Go ahead and upload your file, then <%= mail_to 'contact@letmesingnow.com', 'contact us', :subject => 'Help loading songlist' %> and we'll have you rolling in a jiffy.</p>
<%= jqm_collapsible :collapsed => @dj.songlist?, 'data-content-theme' => :e do %>
  <h3>Upload<% if @dj.songlist? %>
    [<%= @dj.songlist.name %>]
  <% end %></h3>
  <p>Your csv file should have column headings for 'Artist' and 'Title'. Optionally, you may also have columns for 'Song ID', 'Disc', and/or 'Notes'.<p/>
  <%= form_for @dj, :url => songlist_path, :html => {:multipart => true, 'data-ajax' => false} do |f| %>
    <%= jqm_field do %>
      <%= f.label :songlist, "Choose a csv file:" %>
      <%= f.file_field :songlist %>
    <% end %>
    <%= jqm_field do %>
      <%= f.label :remote_songlist_url, "or load from a URL (if your songlist is already online somewhere):" %>
      <%= f.text_field :remote_songlist_url %>
    <% end %>
      <%= f.submit "Upload Songlist" %>
  <% end %>
<% end %>
<%= jqm_collapsible :collapsed => !@dj.songlist?, 'data-content-theme' => :e do %>
  <h3>Import</h3>
  <% if @dj.songlist? %>
    <strong>Import songs from <%= link_to @dj.songlist.name, @dj.songlist_url.to_s, :rel => :external %></strong>
    <%= form_tag load_songlist_path do %>
      <%= jqm_field do %>
        <p>You currently have <%= @dj.songs.count %> songs. Would you like to replace these?</p>
        <%= label_tag :replace, 'Replace current songs' %>
        <%= check_box_tag :replace, :true %>
      <% end if !@dj.songs.empty?%>
      <%= submit_tag("Import Songs") %>
      <em>The import may take a while, depending on the size of your songlist</em>
    <% end %>
  <% else %>
    <strong>Upload a file first.</strong>
  <% end %>
<% end %>

app/views/mobile/songlists/show.html.erb
<h2>Songlist Manager</h2>
<%= jqm_listview do %>
  <%= li_link_to "Browse My Songs", dj_path(@dj) unless @dj.songs.empty? %>
  <%= li_link_to "Import Songlist", import_songlist_path %>
  <%= li_link_to "Export Songlist", export_songlist_path %>
<% end %>