config/routes.rb
Lmsn2::Application.routes.draw do

  resources :song_requests do
    get 'archive', :on => :member
    get 'unarchive', :on => :member
  end

  resources :singers
  
  resource :songlist, :except => [:create, :edit, :delete] do
    get 'import','export'
    post 'load'
  end

  resources :djs, :except => [:new, :create] do
    resources :songs do
      match 'request' => 'song_requests#new'
      get 'search', :on => :collection
      resources :song_requests, :only => :new
    end
    resources :artists, :only => [:index,:show]
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "pages#index"
  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /djs/:dj_id/artists
  # GET /djs/:dj_id/artists.json
  def index
    @dj = Dj.find(params[:dj_id])
    @artists = @dj.artists.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /djs/:dj_id/artists/:id
  # GET /djs/:dj_id/artists/:id.json
  def show
    @dj = Dj.find(params[:dj_id])
    @artist = params[:id]
    @songs = @dj.songs_by_artist(@artist).page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @songs }
    end
  end

end

app/helpers/mobile_helper.rb
#Helpers for mobile views
module MobileHelper

end

app/views/mobile/artists/index.html.erb
<h2><%= link_to @dj.name, @dj %>/Artists</h2>
<%#= page_entries_info(@artists).html_safe %>
<%= paginate @artists %>
<%= jqm_listview do %>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to dj_artist_path(@dj,URI.escape(artist.artist,/\W/)) do %>
        <%= artist.artist %>
        <%= content_tag(:span,artist.count,:class => 'ui-li-count') %>
      <% end %>
    </li>
  <% end %>
<% end %>
<%= paginate @artists %>

app/views/mobile/artists/show.html.erb
<h2><%= link_to @dj.name, @dj %>/Songs by <%= @artist %></h2>
<%= paginate @songs %>
<%= jqm_listview do %>
  <% @songs.each do |song| %>
    <li><%= link_to song.title, new_dj_song_song_request_path(@dj,song) %></li>
  <% end %>
<% end %>
<%= paginate @songs %>